### PR TITLE
Warn user if custom fig.path is ignored

### PR DESCRIPTION
**Pull request by jdblischak**
* Insert warning into HTML noting that custom fig.path was set
* Add footnote to "Getting started" vignette
* Add paragraph to vignette on workflowr implementation

Addresses #114. @lazappi please review.

### CODE REVIEW

**Comment by jdblischak** [comment]
Here's what it looks like when the user sets `fig.path` for one specific chunk. Note that the color will change based on the Bootstrap theme that is used.

screenshot from 2018-08-07 15-25-15

**Comment by pcarbo** [comment]
@jdblischak Nice!

**Comment by jdblischak** [comment]
And if the user sets `fig.path` globally, i.e. `opts_chunk$set(fig.path = "path/")`, each plot will produce a warning.

screenshot from 2018-08-07 15-28-38

**Comment by lazappi** [comment]
That looks like it works to me. Just one thought, is it necessary to put the warnings in the document itself? Given that this doesn't affect how things actually work I would have thought it was sufficient to output a warning to the console that the user can choose to fix/ignore, but maybe you have a reason for doing it this way? It's just a design choice though so whatever you think is the best fit for workflowr.

**Comment by jdblischak** [comment]
Thanks for the review, @lazappi !

> is it necessary to put the warnings in the document itself? Given that this doesn't affect how things actually work I would have thought it was sufficient to output a warning to the console that the user can choose to fix/ignore, but maybe you have a reason for doing it this way? It's just a design choice though so whatever you think is the best fit for workflowr.

Good point. I also explored this option. The problem is that the most accurate way to determine if the user configured `fig.path` is to check while the file is being knit. If I execute `warning()` while the file is being knit, then the warning text gets sent to the standard error log file that workflowr creates (which means the user will likely never see it).

To be able to issue the warning before or after knitting the file, I'd have to parse the file to guess if the user has configured `fig.path`. But I can imagine too many edge cases if I tried to do something like `grep` for the pattern `fig.path` inside of a code chunk: that line may be commented out, the code that configures `fig.path` may be `source`'d from a separate R file, etc.

**Comment by jdblischak** [comment]
I rebased and merged this PR into the dev branch at the command-line: 686b0121776da8180acdb7de8aa5bc3ae0ceada0

**Pull request closed without merging**
