### PR TITLE
Add some tests for wflow_start_rstudio

### PR DESCRIPTION
**Pull request by anhtr**
## Summary
Hello @jdblischak, thank you for the opportunity to contribute to workflowr. As we have discussed, I added a few unit tests for `wflow_start_rstudio`. So far they are based on `wflow_start` tests with updated syntax for `wflow_start_rstudio`. I went though those test and picked out ones that seemed appropriate for the rstudio version. I create this pull request so that the code could be checked. If everything went through, please review and allow this branch to be merged.

Sincerely,
Anh Tran.

## Checklist

- [x] I agree to follow the [Code of Conduct][conduct]
- [x] I have read the [contributing guidelines][contributing]
- [x] I ran the script [scripts/contribute.R][contribute.R]

[conduct]: https://github.com/jdblischak/workflowr/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/jdblischak/workflowr/blob/master/CONTRIBUTING.md
[contribute.R]: https://github.com/jdblischak/workflowr/blob/master/scripts/contribute.R

### CODE REVIEW

**Comment by anhtr** [comment]
It seems like most of the test won't work unless setting `change_wd = FALSE` which is not an option in `wflow_start_rstudio`.

**Review by jdblischak — CHANGES_REQUESTED** [review]
@trannhatanh89 This is great! Once you switch to using `on.exit()`, these tests should pass.

There's only one more test I'd like to see included: throwing an error if the Git user.name and user.email aren't configured.

https://github.com/jdblischak/workflowr/blob/master/tests/testthat/test-wflow_start.R#L204

You can copy-paste it, and then change the expected error message:

https://github.com/jdblischak/workflowr/blob/master/tests/testthat/test-wflow_start.R#L216

https://github.com/jdblischak/workflowr/blob/master/R/wflow_start_rstudio.R#L29

Please let me know if you have any questions. Thanks!

**Review by jdblischak — APPROVED** [review]

**Comment by jdblischak** [comment]
@trannhatanh89 Thanks for contributing to workflowr!

**Comment by anhtr** [comment]
@jdblischak, thank you for approving the pull request. I wanted to wait for checks to pass last night before asking you to re-review, but i guess i fell asleep. =_=

**Comment by jdblischak** [comment]
@trannhatanh89 Heads up. You may need to fix your `.gitconfig` file on your local machine. This should do it:

```
cp ~/.gitconfig-workflowr ~/.gitconfig
```

The issue is that `local_no_gitconfig()` uses the withr package to temporarily move `.gitconfig`, and withr relies on `on.exit()`. By calling a subsequent `on.exit()` without including `add = TRUE`, the withr `on.exit()` to restore `.gitconfig` is erased.

Sorry for the inconvenience. I fixed the issue in 3398e785a53a48ebb7f380c9639075b1f80abaec

**Pull request merged**
