### PR TITLE
Vignette - Sharing common code across analyses

### PR DESCRIPTION
**Pull request by timtrice**
John, apologies for not getting this completed.

### CODE REVIEW

**Comment by jdblischak** [comment]
Thanks for getting this started @timtrice! I'll polish it and then it'd be great if you could review my changes.

For future reference, this PR is the result of the discussion in Issue #111

**Comment by jdblischak** [comment]
@timtrice Also note that I rebased and then merged. This keeps the commit history easy to follow, but it does change the SHA1 of your commit. The consequence of this is that it will be a bit more difficult for you to update your dev branch.

There are various ways to deal with this. One way is to discard your commit and then pull from my repo:

```
cd workflowr
git checkout dev
# Erase your most recent commit
git reset --hard HEAD~1
# Add my repo as a remote
# If you use SSH
git remote add upstream git@github.com:jdblischak/workflowr.git
# alternate if you use HTTPS
git remote add upstream https://github.com/jdblischak/workflowr.git
# Pull from my repo to pull in your commit plus all the other recent changes
git pull upstream dev
```

Please let me know if you have any questions about this.

**Comment by jdblischak** [comment]
@timtrice I've edited the vignette. Could you please review/approve my changes?

https://github.com/jdblischak/workflowr/blob/dev/vignettes/wflow-07-common-code.Rmd

Also, I added you as a contributor in https://github.com/jdblischak/workflowr/commit/30f2e0344284587ef223631b16c8c4719adb621b.

**Comment by jdblischak** [comment]
@timtrice Just a reminder. Could please you give the vignette a quick proofread to make sure there aren't any obvious mistakes?

**Comment by timtrice** [comment]
John, this looks good. But it seems I can generate plots now without changing the `knit_root_dir` setting. Is this expected or have I forgotten something?

**Comment by jdblischak** [comment]
@timtrice Thanks for reviewing the vignette!

> But it seems I can generate plots now without changing the `knit_root_dir` setting. Is this expected or have I forgotten something?

That is unexpected. I just tested it again and still observe the behavior described in the vignette. To summarize:

* Use child document via chunk option -> **no figures**
* Use child document via `knit_expand()` and `knit_root_dir: "."` -> **no figures**
* Use child document via `knit_expand()` and `knit_root_dir: "analysis"` -> **figures**

**Comment by timtrice** [comment]
John, I wasn't able to replicate it in rstudio.cloud so I clearly did something wrong. I think everything is set now.

**Comment by jdblischak** [comment]
@timtrice Great! Thanks for your help!

**Pull request merged**
