### PR TITLE
Update wflow-05-faq.Rmd

### PR DESCRIPTION
**Pull request by johnsonlab**
Edited FAQ to include workflowr/Beaker Browser method for direct sharing of entire site(s) using dat:// links.

### CODE REVIEW

**Comment by jdblischak** [comment]
@johnsonlab Thank you very much for the PR!

My only two concerns are

1. It is a bit verbose for an FAQ entry
1. I feel too self-conscious to have phrases like "truly revelatory" in the documentation (it's flattering coming from a user, but it's to self-congratulating to be in the software's own documentation)

Here's my proposal:

1. I'll merge your PR
1. I'll edit your text and post my changes here so that you can see them

Since this is your first PR on GitHub, I figured this would be easier than having you update your PR by adding additional commits to the branch of your fork. Does this work for you?

**Comment by johnsonlab** [comment]
I accept your proposal and appreciate your understanding given this is my first pull request. Please edit accordingly and I will match the tone and limit verbosity next time. Thanks!

**Comment by jdblischak** [comment]
Great. Congrats on getting your first GitHub PR merged! I'm honored it was for one of my projects!

**Comment by johnsonlab** [comment]
Thanks John - totally my pleasure and thanks for talking me through the
pull request process. It won't be my last!

**Comment by jdblischak** [comment]
I restructured the FAQ in commit https://github.com/jdblischak/workflowr/commit/386a0e2057bdb7901021379590f4ad5d4fae840a. It'll be live in the online docs after the next release.

Cross-referencing Issue #59 here for future reference.

I look forward to your next PR!

**Comment by jdblischak** [comment]
@johnsonlab Thanks again for your contribution! Your FAQ is now live online:

https://jdblischak.github.io/workflowr/articles/wflow-05-faq.html#can-i-share-workflowr-websites-directly-with-collaborators-in-a-secure-fashion

**Pull request merged**
