### PR TITLE
Start issue templates

### PR DESCRIPTION
**Pull request by jdblischak**
One for bug reports and one feature requests.

### CODE REVIEW

**Comment by jdblischak** [comment]
@pcarbo Please push your edits to the [issue-templates branch](https://github.com/jdblischak/workflowr/tree/issue-templates). Thanks!

**Comment by jdblischak** [comment]
And @pcarbo please let me know when you are ready to merge. I'll handle the merge because I want to rebase the commits first.

**Comment by pcarbo** [comment]
@jdblischak I think in this case it is simpler to edit directly on the master because there is no way to see how they look when I create a new Issue. 

What you created looks pretty good, but I would simplify this and not over-prescribe. The key point is to make sure they include package version and sessionInfo.

**Comment by jdblischak** [comment]
>  I think in this case it is simpler to edit directly on the master because there is no way to see how they look when I create a new Issue.

I am planning on merging these into the dev branch before merging them into the master branch. The Markdown text will be inserted into the body of the Issue when a GitHub user opens a new Issue (after selecting "bug report" or "feature request").

**Comment by jdblischak** [comment]
Implemented in 5fe66684b1c689d2e007c0f24ef733fc329e6a10

**Pull request closed without merging**
