### PR TITLE
added .Rprofile file to infrastructure

### PR DESCRIPTION
**Pull request by vanAmsterdam**
for conveniance I've added an .Rprofile file with `library(workflowr)` to skip having to load the package when switching projects in RStudio

### CODE REVIEW

**Comment by jdblischak** [comment]
Thanks for the Pull Request, @vanAmsterdam!

The [Travis build](https://travis-ci.org/jdblischak/workflowr/jobs/295203072) failed because they are having an [issue with their Linux builds](https://www.traviscistatus.com/incidents/4vdl52d28hz3). I've re-started the build.

**Comment by jdblischak** [comment]
I like this idea! It would be convenient to not have to load workflowr at the beginning of each session.

Some things to consider:

1. Is this too much R "magic"? Newer R users will be less familiar with `.Rprofile`, so we'd need to explain in the documentation why they don't need to manually load workflowr. An alternative would be to add a FAQ question that explains how a user can manually add a `.Rprofile` file.

2. Do we need to have a fallback in case a user (or one of their collaborators) clones the workflowr project from GitHub but hasn't yet installed the workflowr R package? I was thinking something like this:

    ```
    if(require("workflowr", quietly = TRUE)) {
      library("workflowr")
    }
    ``` 
1. Will this pass `R CMD build/check`? They have trouble with some hidden files. An alternative would be to write a function that creates this file during `wflow_start()`. Hopefully the CI builds will be informative for this.

@pcarbo Can you think of anything else we should be considering?

**Comment by pcarbo** [comment]
@jdblischak I think this is a wonderful idea and potentially could be expanded on. My only two recommendations would be (1) diligently post messages with in the profile to explain to the user what is going on, and (2) as you said, make sure that the `.Rprofile` code will work on all setups. For item 1, you could do something like:

```R
message("Loading .Rprofile from singlecell_de workflowr project.")
library(workflowr,quietly = FALSE)
wflow_status()
```

The Efficient R Programming book has a [great section](https://csgillespie.github.io/efficientR/set-up.html) on the `.Rprofile` file.

**Comment by vanAmsterdam** [comment]
thanks for the suggestions. 

I've updated the .Rprofile file and added a line in the 'getting started' documentation.

Tests from `testthat.R` failed with `devtools::check()`, but these were unrelated to this pull request

**Comment by jdblischak** [comment]
> I've updated the .Rprofile file and added a line in the 'getting started' documentation.

Great! I like the message in the `.Rprofile` and also the documentation in the vignette.

> Tests from testthat.R failed with devtools::check(), but these were unrelated to this pull request

Could you please share with me the error messages you received? Learning what is causing you errors will help me make workflowr more robust when running on different operating systems.

I don't think the current strategy of adding `inst/infrastructure/.Rprofile` is going to work. When building the package tarball, the `.Rprofile` file gets ignored. The code below reproduces the issue (`workflowr` is the directory with the Git repository with your changes in it):

```
# Confirm that .Rprofile exists in the package source
ls -a workflowr/inst/infrastructure/
# Build the package tarball
R CMD build workflowr
# Install workflowr from the tarball
R CMD INSTALL workflowr_0.7.0.9000.tar.gz 
# Create a test workflowr project
Rscript -e 'workflowr::wflow_start("/tmp/test")'
# Confirm that .Rprofile was not added to new project
ls  -a /tmp/test
```

Thus I think workflowr will need to generate `.Rprofile`. It already does this for `.nojekyll` ([line](https://github.com/jdblischak/workflowr/blob/9c259e915a7f67cfceab4c9521409e8342428673/R/git.R#L50)) and `.gitignore` ([line](https://github.com/jdblischak/workflowr/blob/9c259e915a7f67cfceab4c9521409e8342428673/R/git.R#L50)). This could be accomplished by creating a function, e.g. `create_rprofile`, in `R/wflow_start.R` that behaves similarly to `create_gitignore`.

You've already done a great job getting this feature started. You are welcome to continue working on this. However, if you'd prefer to not spend more time, I can merge this PR and finish the implementation of the feature. Please just let me know how you'd like to proceed. Thanks so much!

**Comment by vanAmsterdam** [comment]
thanks, I've updated the PR. I really like the concept of workflowr, probably I'll keep using it and maybe add some other PRs in the future

Aside from this PR, I get this error whith devtools::check()

Running 'testthat.R' [247s]
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  Running tests in test-wflow_update.R
  testthat results ================================================================
  OK: 596 SKIPPED: 1 FAILED: 9
  1. Failure: obtain_existing_paths works with relative path to home directory (@test-obtain_existing_path.R#51) 
  2. Failure: obtain_existing_paths works with relative path to home directory (@test-obtain_existing_path.R#52) 
  3. Failure: obtain_existing_paths works with relative path to home directory (@test-obtain_existing_path.R#53) 
  4. Failure: obtain_existing_paths works with relative path to home directory (@test-obtain_existing_path.R#54) 
  5. Failure: obtain_existing_paths works with relative path to home directory (@test-obtain_existing_path.R#55) 
  6. Failure: verbose = FALSE suppresses all output (@test-wflow_convert.R#141) 
  7. Failure: verbose = FALSE suppresses all output (@test-wflow_convert.R#144) 
  8. Failure: wflow_start throws an error if user.name and user.email are not set (@test-wflow_start.R#190) 
  9. Failure: wflow_start throws an error if user.name and user.email are not set (@test-wflow_start.R#192)

**Comment by jdblischak** [comment]
@vanAmsterdam This is great! I tested it out and it works well. One thing to note, especially if users start having problems, is that RStudio loads the .Rprofile even if R is started from a subdirectory (e.g. `analysis/`), but R does not.

> thanks, I've updated the PR. I really like the concept of workflowr, probably I'll keep using it and maybe add some other PRs in the future

Awesome! I'm glad you are enjoying using workflowr, and even more glad that you are interested in helping develop it. Please feel free to submit small PRs like this one, but for anything larger, I'd recommend opening an Issue first to discuss.

> I get this error whith devtools::check()

Are you running Windows? I don't get these errors on either Ubuntu or macOS. Could you please send me the output from `sessionInfo()` and `.Platform`?

**Comment by jdblischak** [comment]
I added units tests and made a few tweaks in https://github.com/jdblischak/workflowr/commit/db57a9ad70585abeef765260064dc74a667dea44. The changes were mostly cosmetic. The most substantial change was making sure .Rprofile was committed when the project is created.

Thanks again for the Pull Request!

**Comment by vanAmsterdam** [comment]
cool, thanks. 

here's the info:
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Dutch_Netherlands.1252  LC_CTYPE=Dutch_Netherlands.1252   
[3] LC_MONETARY=Dutch_Netherlands.1252 LC_NUMERIC=C                      
[5] LC_TIME=Dutch_Netherlands.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] workflowr_0.7.0 rmarkdown_1.6  

loaded via a namespace (and not attached):
 [1] compiler_3.4.1  backports_1.1.0 magrittr_1.5    rprojroot_1.2   htmltools_0.3.6 tools_3.4.1    
 [7] Rcpp_0.12.12    stringi_1.1.5   knitr_1.17      stringr_1.2.0   digest_0.6.12   evaluate_0.10.1
> .Platform
$OS.type
[1] "windows"

$file.sep
[1] "/"

$dynlib.ext
[1] ".dll"

$GUI
[1] "RStudio"

$endian
[1] "little"

$pkgType
[1] "win.binary"

$path.sep
[1] ";"

$r_arch
[1] "x64"

**Comment by jdblischak** [comment]
Great. I opened Issue #76 to try and track down these Windows errors.

Also, your changes are now in the master branch in the 0.8.0 release. Thanks again for contributing to workflowr!

**Pull request merged**
