### PR TITLE
revised fetching of ssh key credentials

### PR DESCRIPTION
**Pull request by jakejh**
## Summary

Hello, I've been having the same issue described in [#173](https://github.com/jdblischak/workflowr/issues/173). I do not have a passphrase for my ssh key. I can git push fine from the command line and the RStudio git pane. The problem seems to be that git2r is not loading the ssh credentials.

I therefore tweaked the `wflow_git_pull`, `wflow_git_push`, and `authenticate_git` functions. I ran scripts/contribute.R and it gave me the green light. Let me know if there's anything else I should do. Thanks.

## Checklist

- [x] I agree to follow the [Code of Conduct][conduct]
- [x] I have read the [contributing guidelines][contributing]
- [x] I ran the script [scripts/contribute.R][contribute.R]

[conduct]: https://github.com/jdblischak/workflowr/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/jdblischak/workflowr/blob/master/CONTRIBUTING.md
[contribute.R]: https://github.com/jdblischak/workflowr/blob/master/scripts/contribute.R

### Using workflowr 1.6.1 from CRAN
```
> git2r::libgit2_features()
$threads
[1] TRUE

$https
[1] TRUE

$ssh
[1] TRUE
```
```
> git2r::cred_ssh_key()
$publickey
[1] "/Users/jake/.ssh/id_rsa.pub"

$privatekey
[1] "/Users/jake/.ssh/id_rsa"

$passphrase
character(0)

attr(,"class")
[1] "cred_ssh_key"
```
```
> wflow_git_pull()
Error: Pull failed for unknown reason.

The error message from git2r::pull() was:

Error in 'git2r_remote_fetch': error authenticating:

These sorts of errors are difficult to troubleshoot. You can search for similar errors on the git2r
GitHub repository for advice on how to fix it.

Alternatively, if you have Git installed on your machine, the easiest solution is to instead run `git
pull` in the terminal. This is equivalent to wflow_git_pull(). Specifically, copy-paste the following
in the terminal:

git pull origin master
```
```
> git2r::pull()
Error in fetch(repo = repo, name = branch_remote_name(upstream_branch),  : 
  Error in 'git2r_remote_fetch': error authenticating: 
```
```
> git2r::pull(credentials = git2r::cred_ssh_key())
Already up-to-date
```

### Using workflowr from this pull request
```
> wflow_git_pull()
Summary from wflow_git_pull

Pulling from the branch "master" of the remote repository "origin" 

Using the SSH protocol
The following Git command was run:

  $ git pull origin master

No changes were made because your local and remote repositories are in sync.
```

### CODE REVIEW

**Comment by jdblischak** [comment]
@jakejh Thanks for the Pull Request! I'll investigate more tomorrow.

And don't worry about the failing AppVeyor build. That's a known issue that I still need to figure out how to fix.

**Comment by jdblischak** [comment]
I tested your PR on my laptop running Ubuntu 18.04. I have SSH keys that have a passphrase. When I set the argument `ssh_key_has_passphrase = TRUE`, `wflow_git_pull()` works without issue. However, if I forget to set the argument when running `wflow_git_pull()`, I am prompted for my passphrase, and then it stalls for a long time (~2 minutes) before eventually throwing an error message:

```
> wflow_git_pull()
Error: workflowr was unable to use your SSH keys because it has a passphrase. You'll need to activate ssh-agent and add your
keys.

Alternatively, if you have Git installed on your machine, the easiest solution is to instead run `git pull` in the
terminal. This is equivalent to wflow_git_pull(). Specifically, copy-paste the following in the terminal:

git pull origin master
```

I don't love that the default behavior when using SSH keys is so unfriendly. Brainstorming:

1. Is there a way we can detect if an SSH key requires a passphrase? At minimum it would be nice to fail early if the user's SSH keys require a passphrase but they didn't configure `ssh_key_has_passphrase`. At best workflowr could automatically handle this without the user having to set an argument.

1. Short-term we'll need a work around that looks something like your PR. But long-term this feels like an issue that should be solved by git2r. I'd like to file an Issue on the git2r repo with a reproducible example. You've done a great job diagnosing the problem, so please let me know if you'd prefer to file the issue yourself.

**Comment by jakejh** [comment]
I think the problem is that `git2r::cred_ssh_key` uses a function called `ssh_key_needs_passphrase` ([here](https://github.com/ropensci/git2r/blob/196318a3248d1c14734ed2dea10bf19b23760899/R/credential.R#L181)), but that function doesn't actually work, at least not for the passphrase-protected key pair I generated. I know next to nothing about public-private key authentication, but I did find [this](https://security.stackexchange.com/questions/129724/how-to-check-if-an-ssh-private-key-has-passphrase-or-not), which suggests a platform-independent solution that may work 99% of the time, especially since workflowr will only ever look for a key named "id_rsa" anyway.

Agreed that a solution within git2r would be better long-term. I leave it to you to file an issue with them.

**Comment by jdblischak** [comment]
I'm having trouble creating a reproducible example to isolate the error. The following works with a key with and without a passphrase:

```
library(git2r)
r <- clone("git@github.com:ropensci/git2r.git", tempfile())
previous_commit <- commits(r)[[2]]
reset(previous_commit, reset_type = "hard")
pull(r)
## Merge: Fast-forward
```

The `clone()` step required the passphrase but not the `pull()` step. Thus I tried doing the setup purely in Git:

```
git clone git@github.com:ropensci/git2r.git
cd git2r/
git reset --hard HEAD~1
```

Then when I tried running `pull()`, it still worked for both types of keys. However, the key with a passphrase didn't require the SSH passphrase. Thus I think Git wasn't fooled by my resetting to a previous commit (i.e. it grabs the commit locally instead of querying GitHub). So I'll have to try a more elaborate setup with a fake repository that I clone and then add a commit before pulling.

```
> packageVersion("git2r")
[1] ‘0.26.1’
> git2r::libgit2_features()
$threads
[1] FALSE

$https
[1] TRUE

$ssh
[1] TRUE

> osVersion
[1] "Ubuntu 18.04.4 LTS"
```

**Comment by jdblischak** [comment]
@jakejh A few more questions to help me continue troubleshooting:

1. Do you use the `-o` flag when creating SSH keys with `ssh-keygen`? If you can't remember, you can check by running `head -n 1 ~/.ssh/id_rsa`. If you set `-o`, it will say `BEGIN OPENSSH PRIVATE KEY`. If not, it'll say `BEGIN RSA PRIVATE KEY`

1. You said that the function `ssh_key_needs_passphrase()` didn't work for you when you create a password-protected key. Could you please share the exact `ssh-keygen` command you ran to create that test key? Also, could you please try the tests I describe in https://github.com/ropensci/git2r/issues/421#issuecomment-621474402 to see if you get the same results?

**Comment by jakejh** [comment]
@jdblischak I simply used `ssh-keygen` for the test key pair. See below. I've been following the git2r issue. Let me know if there's anything I can do here.

```
jake$ ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/Users/jake/.ssh/id_rsa): id_rsa_test
Enter passphrase (empty for no passphrase): <<I entered a passphrase>>
Enter same passphrase again: <<I entered a passphrase>>
Your identification has been saved in id_rsa_test.
Your public key has been saved in id_rsa_test.pub.
The key fingerprint is:
<<omitted>>
The key's randomart image is:
<<omitted>>
jake$ head -n 1 id_rsa_test
-----BEGIN OPENSSH PRIVATE KEY-----
```

**Comment by jdblischak** [comment]
> I simply used `ssh-keygen` for the test key pair.

Thanks, very interesting. The version of OpenSSH you have installed automatically uses the newer OpenSSH format, which is why `ssh_key_needs_passphrase()` didn't work for you.

I'm using [OpenSSH version 7.6 on Ubuntu 18.04](https://packages.ubuntu.com/bionic-updates/openssh-client):

```
$ apt list -a --installed openssh-client
Listing... Done
openssh-client/bionic-updates,bionic-security,now 1:7.6p1-4ubuntu0.3 amd64 [installed,automatic]
openssh-client/bionic 1:7.6p1-4 amd64
```

Looking at the [release notes](https://www.openssh.com/releasenotes.html), the current version of OpenSSH is 8.2, and the OpenSSH format was made the default in version 7.8:

```
* ssh-keygen(1): write OpenSSH format private keys by default
   instead of using OpenSSL's PEM format.
```

Thus all the more reason to update git2r to handle these newer keys.

**Comment by jdblischak** [comment]
@jakejh I apologize that we haven't made much progress on this front. Your PR was nicely implemented and well-formatted, and I really wanted to merge it.

However, as discussed here and in https://github.com/ropensci/git2r/issues/421, the situation with SSH key algorithms and passphrases is quite complex, and I don't it can be handled robustly enough in a downstream package like workflowr. The best options I see going forward are either 1) assist with the integration of the credentials package into git2r (branch [use-credentials-pkg](https://github.com/ropensci/git2r/tree/use-credentials-pkg)), 2) refactor workflowr's Git interface to be more generic, and thus allow use of either git2r or gert as the "git backend". Either of these would require lot of effort, and I unfortunately don't have the bandwidth at the moment to push them forward.

I appreciate your help troubleshooting this issue. Until we find a more robust solution, the best fix is to run Git directly in the terminal or use the RStudio Git Pane for pushing and pulling.

**Comment by jakejh** [comment]
No worries @jdblischak. Happy holidays!

**Comment by jdblischak** [comment]
Thanks @jakejh and same to you!

**Pull request closed without merging**
