### PR TITLE
add support for fig_path_ext option

### PR DESCRIPTION
**Pull request by Tutuchan**
This PR adds support for removing the `.Rmd` extension in the figures paths, _via_ the `fig_path_ext` option as discussed in #119.

I took the liberty of adding two supporting functions in `wflow_options`. I'm open to any comments and modifications.

### CODE REVIEW

**Comment by jdblischak** [comment]
@Tutuchan Thanks for the PR! From a quick look, this looks really good. Only `wflow_remove` has failing tests. I'll investigate this more thoroughly later this week.

**Comment by jdblischak** [comment]
Well this is super frustrating. The `wflow_remove()` tests pass on my local Ubuntu, macOS, and Windows machine. Do the tests pass on your local machine? What OS are you using?

I sent Travis an email to request [debug mode](https://docs.travis-ci.com/user/running-build-in-debug-mode/#enabling-debug-mode) to be enabled.

**Comment by Tutuchan** [comment]
Yes, the tests pass on my local machine (using macOS) as well 🤔. Did you hear back from Travis ?

**Comment by jdblischak** [comment]
> Yes, the tests pass on my local machine (using macOS) as well

That's reassuring. Hopefully it's some quirk on the CI machine that is not too difficult to work around.

> Did you hear back from Travis ?

Yes, they've enabled debug mode and sent me a long set of instructions. I'm going to give them a try today.

**Comment by jdblischak** [comment]
OK. Making some progress. I successfully accessed the build via SSH to interactively debug. A few observations:

1. Reassuringly the `wflow_remove()` tests pass after your latest commit. I swear when I checked those builds after they first failed that they still had failing tests for `wflow_remove()`, but I'm happy to have been mistaken.
2. The current cause of failure is in `build_rmd_external`:
    ```
   1. Failure: An error stops execution, does not create file
            and provides informative error message (@test-build_rmd_external.R#76)
    ```

The error in `build_rmd_external` is unrelated to your PR. It is caused by the new release of callr and processx ([NEWS.md](https://github.com/r-lib/processx/blob/5917b062f4033c3c6cd71fb6b76d012611e04614/inst/NEWS.md)):

> When run() is interrupted, no error message is printed, just like for interruption of R code in general. The thrown condition now also has the interrupt class (#148).

```
travis_run_before_install 
Rscript -e 'packageVersion("callr")'
# [1] ‘2.0.4’
Rscript -e 'packageVersion("processx")'
# [1] ‘3.1.0’
Rscript -e 'devtools::install(dependencies = FALSE)'
# Required to run devtools::test()
Rscript -e 'install.packages("roxygen2")'
# Tests pass
Rscript -e 'devtools::test(filter = "external$")'
Rscript -e 'install.packages("processx")'
Rscript -e 'packageVersion("processx")'
# [1] ‘3.2.0’
# Tests pass
Rscript -e 'devtools::test(filter = "external$")'
Rscript -e 'install.packages("callr")'
Rscript -e 'packageVersion("callr")'
# [1] ‘3.0.0’
# Tests fail
Rscript -e 'devtools::test(filter = "external$")'
```

@Tutuchan I'm going to figure out how difficult it will be to fix this callr error. I'm also going to further test your PR with some unit tests. There's nothing I need from you at the moment, so I'll let you know once I have questions or need you to update anything. I apologize that this has gotten more complicated than it needed to be!

**Comment by jdblischak** [comment]
I pushed a new commit to your branch to try and avoid the callr error by installing a previous version. Fingers crossed!

**Comment by jdblischak** [comment]
@Tutuchan I added some unit tests and then did some minor refactoring. In order to ensure that `create_figure_path()` can determine the setting of `fig_path_ext`, it needs the full path to the R Markdown file. This doesn't make a difference if the workflowr function is run from the project root, but does if it is run from anywhere else.

Please review my changes. If the tests pass and you're satisfied with the changes I made, I'm ready to merge.

**Comment by Tutuchan** [comment]
@jdblischak looks good to me! Some tests seem to fail on AppVeyor but I don't have a Windows machine to debug them.

**Comment by jdblischak** [comment]
> Some tests seem to fail on AppVeyor but I don't have a Windows machine to debug them.

@Tutuchan No need for you to worry about those AppVeyor errors. Those are from code I wrote. I usually try to fix errors like these as quick as possible, but I can't reproduce the errors on my local Windows machine. And debugging AppVeyor is way more cumbersome that debugging Travis because you have to use PowerShell instead of Bash.

**Pull request merged**
